spring:
  application.name: kotlin-springboot-playground
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
springdoc.swagger-ui:
  path: /swagger-ui.html
  use-root-path: true
management:
  endpoints.web.exposure.include: info,health
  info.env.enabled: true
  info.java.enabled: true
  info.git.enabled: true
  info.build.enabled: true
  info.os.enabled: true
  health.db.enabled: true
  endpoint.health:
    show-details: when_authorized
    probes.enabled: true
    group.liveness.include:
    group.readiness.include: db
